Update lib
zehemz/nismian-the-game pull request #2
Opened 2019-01-01 20:54 UTC by luchovl2

Actualiza libgdx a 1.9.9 porque no andaban los skins.
Agrega screen inicial de intro/menu.
Agrega atlas de texturas y lo usa para generar la animaciones.
Arregla el tema del render del sprite. Ahora tiene sentido.
Ah, e implementa un zoom para la cámara para debug o lo que sea.

2019-01-04 18:09 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        Skin skin = new Skin(Gdx.files.internal("skins/craftacular/craftacular-ui.json"));
final

2019-01-04 18:09 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        Table table = new Table();
final

2019-01-04 18:09 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        {
pedofile

2019-01-04 18:09 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/PlayScreen.java
> +            Family family = Family.all(CameraComponent.class).get();
final

2019-01-04 18:10 UTC, zehemz commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setScale(1/16f);
constante?

2019-01-04 18:11 UTC, zehemz commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setScale(1/16f);
El scale no se hacía ya en el ```GameSprite.java```?

2019-01-04 18:11 UTC, zehemz commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setOrigin(0, 0);
si esto va siempre, porque no está en el constructor del ```GameSprite.java```?

2019-01-04 18:12 UTC, zehemz commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setPosition(position.get().x, position.get().y);
hacerlo así no traia problemas?

2019-01-04 18:12 UTC, zehemz requested changes
ver comments

2019-01-04 18:14 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        BitmapFont textFont = skin.getFont("font");
Constante

2019-01-04 18:14 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        BitmapFont titleFont = skin.getFont("title");
Constante

2019-01-04 18:14 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        viewport = new FitViewport(1200, 900,
numero fantasma.

2019-01-04 18:15 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +public class IntroScreen extends ScreenAdapter
Si todas las screens van a tener el mismo tipo de configuración yo haría un abstract baseclass

2019-01-04 18:31 UTC, luchovl2 commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setScale(1/16f);
No encontré dónde mierda hacía el set scale. Lo cambié para agrandarlo. En general depende de cada sprite, a menos que en píxeles ya sean coherentes y se pueda setear una vez para todos.

2019-01-04 18:32 UTC, luchovl2 commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setOrigin(0, 0);
Hay que probar. Me parece que se rompe si no lo hacés cada vez.

2019-01-04 18:34 UTC, luchovl2 commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setPosition(position.get().x, position.get().y);
No. No lo habíamos hecho exactamente así. Así anda bien y tiene sentido.

2019-01-04 18:36 UTC, luchovl2 commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        viewport = new FitViewport(1200, 900,
Sí, es para que la UI se vea bien. O para controlar el tamaño y la proporción de la UI.

2019-01-04 18:38 UTC, luchovl2 commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +public class IntroScreen extends ScreenAdapter
Probablemente tenga sentido.

2019-01-04 18:39 UTC, luchovl2 commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        {
Me vas a hacer caer el fbi... Por poner la llave donde corresponde...

2019-01-06 17:54 UTC, zehemz commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setPosition(position.get().x, position.get().y);
debe ser lo del scale entonces.
Lo que no le veo sentido es hacer eso cada frame.

2019-01-06 17:55 UTC, zehemz commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        viewport = new FitViewport(1200, 900,
no estaría entendiendo de donde sale. además, por que no son constantes de esta clase?

2019-01-07 12:58 UTC, luchovl2 commented on core/src/com/bahoga/nismian/systems/SpriteRenderSystem.java
> +                    gameSprite.sprite.setPosition(position.get().x, position.get().y);
El setOrigin ya lo pasé al constructor del gameSprite y anduvo. El setScale también debería.

2019-01-07 13:06 UTC, luchovl2 commented on core/src/com/bahoga/nismian/sceens/IntroScreen.java
> +        viewport = new FitViewport(1200, 900,
Lo puse a ojo. Si ponía un viewport con las dimensiones de la ventana se veía gigante, y como "no se puede" escalar los elementos de la UI lo achiqué con las dimensiones del viewport. Si no se entiende, correlo y jugá con los números.
No las puse constantes porque estaba probando. Ya las hice constantes. Calmate.

2019-01-09 00:09 UTC, zehemz approved these changes

2019-01-09 00:10 UTC, merged