Anim optimization
zehemz/nismian-the-game pull request #3
Opened 2019-01-04 18:16 UTC by zehemz

Optimización de animaciones - Agregado rotaciones de Sprites provisorios.

2019-01-07 14:39 UTC, guchito9 requested changes

2019-01-07 14:39 UTC, guchemeli commented on core/src/com/bahoga/nismian/components/CameraComponent.java
> +        cam.zoom = 0.5f;
Magic number.

2019-01-08 23:30 UTC, zehemz commented on core/src/com/bahoga/nismian/components/CameraComponent.java
> +        cam.zoom = 0.5f;
jajajaj forro

2019-01-09 00:53 UTC, luchovl2 submitted a review, later dismissed

2019-01-09 00:53 UTC, luchovl2 commented on core/src/com/bahoga/nismian/components/Direction.java
> +        } else if (angle == 180f) {
No es buena idea preguntar por igualdad con floats.
No hace falta usar el ángulo. Si la componente x > 0 entonces va hacia la derecha y así con el resto.

2019-01-09 00:53 UTC, luchovl2 commented on core/src/com/bahoga/nismian/AnimationFactory.java
> +        });
Habrá que ver de usar el TextureAtlas, como en mi branch. Se cargan todas las textures del juego de una y luego se toman las texture regions que se quieren.

2019-01-09 00:54 UTC, zehemz commented on core/src/com/bahoga/nismian/components/Direction.java
> +        } else if (angle == 180f) {
si

2019-01-09 01:00 UTC, luchovl2 approved these changes

2019-01-09 01:00 UTC, merged